/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BundleSubscriptionRouteImport } from './routes/bundle-subscription'
import { Route as InternationalSubscriptionRouteImport } from './routes/international-subscription'
import { Route as OrderFormRouteImport } from './routes/order-form'
import { Route as OrderFormInternationalRouteImport } from './routes/order-form-international'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PaymentResponseRouteImport } from './routes/payment-response'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleSubscriptionRoute = BundleSubscriptionRouteImport.update({
  id: '/bundle-subscription',
  path: '/bundle-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalSubscriptionRoute =
  InternationalSubscriptionRouteImport.update({
    id: '/international-subscription',
    path: '/international-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrderFormRoute = OrderFormRouteImport.update({
  id: '/order-form',
  path: '/order-form',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderFormInternationalRoute = OrderFormInternationalRouteImport.update({
  id: '/order-form-international',
  path: '/order-form-international',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResponseRoute = PaymentResponseRouteImport.update({
  id: '/payment-response',
  path: '/payment-response',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bundle-subscription': typeof BundleSubscriptionRoute
  '/international-subscription': typeof InternationalSubscriptionRoute
  '/order-form': typeof OrderFormRoute
  '/order-form-international': typeof OrderFormInternationalRoute
  '/payment': typeof PaymentRoute
  '/payment-response': typeof PaymentResponseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bundle-subscription': typeof BundleSubscriptionRoute
  '/international-subscription': typeof InternationalSubscriptionRoute
  '/order-form': typeof OrderFormRoute
  '/order-form-international': typeof OrderFormInternationalRoute
  '/payment': typeof PaymentRoute
  '/payment-response': typeof PaymentResponseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bundle-subscription': typeof BundleSubscriptionRoute
  '/international-subscription': typeof InternationalSubscriptionRoute
  '/order-form': typeof OrderFormRoute
  '/order-form-international': typeof OrderFormInternationalRoute
  '/payment': typeof PaymentRoute
  '/payment-response': typeof PaymentResponseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bundle-subscription'
    | '/international-subscription'
    | '/order-form'
    | '/order-form-international'
    | '/payment'
    | '/payment-response'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bundle-subscription'
    | '/international-subscription'
    | '/order-form'
    | '/order-form-international'
    | '/payment'
    | '/payment-response'
  id:
    | '__root__'
    | '/'
    | '/bundle-subscription'
    | '/international-subscription'
    | '/order-form'
    | '/order-form-international'
    | '/payment'
    | '/payment-response'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BundleSubscriptionRoute: typeof BundleSubscriptionRoute
  InternationalSubscriptionRoute: typeof InternationalSubscriptionRoute
  OrderFormRoute: typeof OrderFormRoute
  OrderFormInternationalRoute: typeof OrderFormInternationalRoute
  PaymentRoute: typeof PaymentRoute
  PaymentResponseRoute: typeof PaymentResponseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle-subscription': {
      id: '/bundle-subscription'
      path: '/bundle-subscription'
      fullPath: '/bundle-subscription'
      preLoaderRoute: typeof BundleSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-subscription': {
      id: '/international-subscription'
      path: '/international-subscription'
      fullPath: '/international-subscription'
      preLoaderRoute: typeof InternationalSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-form': {
      id: '/order-form'
      path: '/order-form'
      fullPath: '/order-form'
      preLoaderRoute: typeof OrderFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-form-international': {
      id: '/order-form-international'
      path: '/order-form-international'
      fullPath: '/order-form-international'
      preLoaderRoute: typeof OrderFormInternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-response': {
      id: '/payment-response'
      path: '/payment-response'
      fullPath: '/payment-response'
      preLoaderRoute: typeof PaymentResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BundleSubscriptionRoute: BundleSubscriptionRoute,
  InternationalSubscriptionRoute: InternationalSubscriptionRoute,
  OrderFormRoute: OrderFormRoute,
  OrderFormInternationalRoute: OrderFormInternationalRoute,
  PaymentRoute: PaymentRoute,
  PaymentResponseRoute: PaymentResponseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
